service: fm-nextjs-docker

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  memorySize: 256

custom:
  debug:
    prd: middlewares:*
    dev: middlewares:*

functions:
  index:
    timeout: 30
    image: 799791150485.dkr.ecr.ap-southeast-1.amazonaws.com/fm-nextjs-docker:2c74830ac370ee5c195a87d084910c4750155b25
    environment:
      SERVICE_NAME: '${self:service}-${opt:stage, self:provider.stage}'
      DEBUG: ${self:custom.debug.${opt:stage, self:provider.stage}}
      STAGE: ${opt:stage, self:provider.stage}
      # AWS_LAMBDA_RUNTIME_VERBOSE: 3
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
